name: "PR Jukebox"

on:
  pull_request:
    types: [opened]

jobs:
  suggest-song:
    runs-on: ubuntu-latest
    permissions:
        pull-requests: write
    steps:
      - name: "Run PR Jukebox"
        uses: amaziahub/pr-jukebox@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
